apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lmxahw5hx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lmxahw5hx-nodejs 
  name: lmxahw5hx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lmxahw5hx-nodejs 
